spring:
  datasource:
    tenant1 :
      url: jdbc:postgresql://localhost:5432/tenant1
      username: postgre
      password: fasoo
      driver-class-name: org.postgresql.Driver
    tenant2 :
      url: jdbc:postgresql://localhost:5432/tenant2
      username: postgre
      password: fasoo
      driver-class-name: org.postgresql.Driver
