spring:
  datasource:
    tenants :
      default:
        url: jdbc:mysql://multitenancy.ctaoexhweli2.ap-northeast-2.rds.amazonaws.com:3306/tenant1
        username: root
        password: dkssud003512!!
        driver-class-name: com.mysql.cj.jdbc.Driver
      tenant1:
        url: jdbc:mysql://multitenancy.ctaoexhweli2.ap-northeast-2.rds.amazonaws.com:3306/tenant1
        username: root
        password: dkssud003512!!
        driver-class-name: com.mysql.cj.jdbc.Driver
      tenant2:
        url: jdbc:mysql://multitenancy.ctaoexhweli2.ap-northeast-2.rds.amazonaws.com:3306/tenant2
        username: root
        password: dkssud003512!!
        driver-class-name: com.mysql.cj.jdbc.Driver
