spring:
  datasource:
    tenants:
      default:
        uri: jdbc:postgresql://localhost:5432/tenant1
        username: postgres
        password: fasoo
        driver-class-name: org.postgresql.Driver
      tenant1 :
        uri: jdbc:postgresql://localhost:5432/tenant1
        username: postgres
        password: fasoo
        driver-class-name: org.postgresql.Driver
      tenant2:
        uri: jdbc:postgresql://localhost:5432/tenant2
        username: postgres
        password: fasoo
        driver-class-name: org.postgresql.Driver

name :
  name : minjin
