#my-config.name : dev
#
#spring :
#  datasource : 
#    db_a :
#      uri : da_a
#      username : root
#      password : password
#      driver-class-name : org.postgresql.Driver
#
#    db_b :
#      uri : da_b
#      username : root
#      password : password
#      driver-class-name : org.postgresql.Driver
#
#management :
#  endpoints :
#    web:
#      exposure :
#        include : "*"
#  endpoint :
#    shutdown :
#      enabled : true

spring:
  datasource:
    tenants:
      default:
        url: jdbc:postgresql://localhost:5432/tenant1
        username: postgres
        password: fasoo
        driver-class-name: org.postgresql.Driver
        version: dev
      tenant1 :
        url: jdbc:postgresql://localhost:5432/tenant1
        username: postgres
        password: fasoo
        driver-class-name: org.postgresql.Driver
        version: dev
      tenant2:
        url: jdbc:postgresql://localhost:5432/tenant2
        username: postgres
        password: fasoo
        driver-class-name: org.postgresql.Driver
        version: dev
